/**
 * generate-context.ts — Auto-generates machine-readable context files for AI agents.
 *
 * Extracts exports, schema tables, and API routes from TypeScript source files
 * and writes them to .context/ as markdown summaries. These files help AI agents
 * verify file/function/table existence before referencing them (anti-hallucination).
 *
 * Usage:
 *   pnpm context:generate
 *   tsx scripts/generate-context.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const CONTEXT_DIR = path.join(ROOT, ".context");
const timestamp = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");

// ─── Helpers ────────────────────────────────────────────────────────────────

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function readFile(relPath: string): string {
  const abs = path.join(ROOT, relPath);
  if (!fs.existsSync(abs)) return "";
  return fs.readFileSync(abs, "utf-8");
}

function extractExports(source: string): { types: string[]; values: string[]; schemas: string[] } {
  const types: string[] = [];
  const values: string[] = [];
  const schemas: string[] = [];

  // Match: export { Name1, Name2 } or export type { Name1, Name2 }
  // Match: export { type Name1, Name2 }
  const lines = source.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    // Extract individual export names from the line
    // Look for named things: type Foo, Foo (constant/function)
    const typeMatches = trimmed.matchAll(/\btype\s+([A-Z][A-Za-z0-9]+)/g);
    for (const m of typeMatches) {
      types.push(m[1]);
    }

    // Look for value exports (uppercase constants like ISSUE_STATUSES)
    const constMatches = trimmed.matchAll(/\b([A-Z][A-Z_]{2,}[A-Z0-9])\b/g);
    for (const m of constMatches) {
      if (!m[1].startsWith("API") || m[1] === "API" || m[1] === "API_PREFIX") {
        values.push(m[1]);
      }
    }

    // Look for schema exports (camelCase ending in Schema)
    const schemaMatches = trimmed.matchAll(/\b([a-z][A-Za-z0-9]*Schema)\b/g);
    for (const m of schemaMatches) {
      schemas.push(m[1]);
    }

    // Look for function exports (camelCase that are not schemas or types)
    const funcMatches = trimmed.matchAll(/\b((?:create|update|get|build|parse|extract|normalize|derive|interpolate|is|stringify|sync|has)[A-Za-z0-9]+)\b/g);
    for (const m of funcMatches) {
      if (!m[1].endsWith("Schema")) {
        values.push(m[1]);
      }
    }
  }

  return {
    types: [...new Set(types)].sort(),
    values: [...new Set(values)].sort(),
    schemas: [...new Set(schemas)].sort(),
  };
}

function extractSchemaExports(source: string): string[] {
  const tables: string[] = [];
  const lines = source.split("\n");
  for (const line of lines) {
    // Match: export { tableName } from "./file.js";
    const m = line.match(/export\s*\{([^}]+)\}\s*from/);
    if (m) {
      const names = m[1].split(",").map((n) => n.trim()).filter(Boolean);
      tables.push(...names);
    }
  }
  return tables;
}

function extractRoutes(source: string): { method: string; path: string }[] {
  const routes: { method: string; path: string }[] = [];
  const lines = source.split("\n");
  for (const line of lines) {
    // Match: router.get("/path", ...) or router.post("/path", ...)
    const m = line.match(/router\.(get|post|put|patch|delete)\s*\(\s*["'`]([^"'`]+)["'`]/);
    if (m) {
      routes.push({ method: m[1].toUpperCase(), path: m[2] });
    }
    // Match: app.use("/api/path", routerName)
    const mountMatch = line.match(/app\.use\s*\(\s*["'`]([^"'`]+)["'`]/);
    if (mountMatch) {
      routes.push({ method: "MOUNT", path: mountMatch[1] });
    }
  }
  return routes;
}

// ─── Generators ─────────────────────────────────────────────────────────────

function generateSharedExports(): string {
  const source = readFile("packages/shared/src/index.ts");
  if (!source) return "# Error: packages/shared/src/index.ts not found\n";

  const { types, values, schemas } = extractExports(source);

  let md = `# @paperclipai/shared — Public Exports\n\n`;
  md += `> Auto-generated by \`scripts/generate-context.ts\` on ${timestamp}\n`;
  md += `> **DO NOT EDIT.** Regenerate with: \`pnpm context:generate\`\n\n`;
  md += `Source: \`packages/shared/src/index.ts\` (${source.split("\n").length} lines)\n\n`;

  md += `## Types (${types.length})\n\n`;
  md += `| Name |\n|------|\n`;
  for (const t of types) md += `| ${t} |\n`;

  md += `\n## Constants & Functions (${values.length})\n\n`;
  md += `| Name |\n|------|\n`;
  for (const v of values) md += `| ${v} |\n`;

  md += `\n## Validation Schemas (${schemas.length})\n\n`;
  md += `| Name |\n|------|\n`;
  for (const s of schemas) md += `| ${s} |\n`;

  return md;
}

function generateSchemaSnapshot(): string {
  const barrelSource = readFile("packages/db/src/schema/index.ts");
  if (!barrelSource) return "# Error: packages/db/src/schema/index.ts not found\n";

  const tableNames = extractSchemaExports(barrelSource);

  let md = `# @paperclipai/db — Schema Tables\n\n`;
  md += `> Auto-generated by \`scripts/generate-context.ts\` on ${timestamp}\n`;
  md += `> **DO NOT EDIT.** Regenerate with: \`pnpm context:generate\`\n\n`;
  md += `Source: \`packages/db/src/schema/index.ts\`\n\n`;
  md += `## Exported Tables (${tableNames.length})\n\n`;
  md += `| Export Name | Source File |\n|-------------|-------------|\n`;

  // Also extract source files
  const lines = barrelSource.split("\n");
  for (const line of lines) {
    const m = line.match(/export\s*\{([^}]+)\}\s*from\s*["'`]\.\/([^"'`]+)["'`]/);
    if (m) {
      const names = m[1].split(",").map((n) => n.trim()).filter(Boolean);
      const file = m[2];
      for (const name of names) {
        md += `| \`${name}\` | \`schema/${file}\` |\n`;
      }
    }
  }

  // List all schema files with their table names
  const schemaDir = path.join(ROOT, "packages/db/src/schema");
  if (fs.existsSync(schemaDir)) {
    const files = fs.readdirSync(schemaDir).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort();
    md += `\n## Schema Source Files (${files.length})\n\n`;
    md += `| File | Size |\n|------|------|\n`;
    for (const file of files) {
      const stat = fs.statSync(path.join(schemaDir, file));
      md += `| \`${file}\` | ${stat.size} bytes |\n`;
    }
  }

  return md;
}

function generateApiSurface(): string {
  const routesDir = path.join(ROOT, "server/src/routes");
  if (!fs.existsSync(routesDir)) return "# Error: server/src/routes/ not found\n";

  const routeFiles = fs.readdirSync(routesDir).filter((f) => f.endsWith(".ts")).sort();

  let md = `# Paperclip API Surface\n\n`;
  md += `> Auto-generated by \`scripts/generate-context.ts\` on ${timestamp}\n`;
  md += `> **DO NOT EDIT.** Regenerate with: \`pnpm context:generate\`\n\n`;

  // Read app.ts for mount points
  const appSource = readFile("server/src/app.ts");
  const mounts = extractRoutes(appSource).filter((r) => r.method === "MOUNT");

  if (mounts.length) {
    md += `## Route Mounts (from app.ts)\n\n`;
    md += `| Mount Path | Router |\n|------------|--------|\n`;
    for (const m of mounts) {
      md += `| \`${m.path}\` | (see route file) |\n`;
    }
    md += "\n";
  }

  // Per-file route extraction
  md += `## Route Files (${routeFiles.length})\n\n`;
  for (const file of routeFiles) {
    const source = fs.readFileSync(path.join(routesDir, file), "utf-8");
    const routes = extractRoutes(source);

    md += `### \`routes/${file}\`\n\n`;
    if (routes.length) {
      md += `| Method | Path |\n|--------|------|\n`;
      for (const r of routes) {
        md += `| ${r.method} | \`${r.path}\` |\n`;
      }
    } else {
      md += `_(no standard routes detected — may use dynamic registration)_\n`;
    }
    md += "\n";
  }

  return md;
}

function generateAdapterRegistry(): string {
  const adaptersDir = path.join(ROOT, "packages/adapters");
  if (!fs.existsSync(adaptersDir)) return "# Error: packages/adapters/ not found\n";

  const adapterDirs = fs.readdirSync(adaptersDir).filter((d) => {
    return fs.statSync(path.join(adaptersDir, d)).isDirectory() && !d.startsWith(".");
  }).sort();

  let md = `# Adapter Registry\n\n`;
  md += `> Auto-generated by \`scripts/generate-context.ts\` on ${timestamp}\n`;
  md += `> **DO NOT EDIT.** Regenerate with: \`pnpm context:generate\`\n\n`;
  md += `## Built-in Adapters (${adapterDirs.length})\n\n`;
  md += `| Package | Directory | Has Server | Has UI |\n`;
  md += `|---------|-----------|------------|--------|\n`;

  for (const dir of adapterDirs) {
    const pkgPath = path.join(adaptersDir, dir, "package.json");
    let pkgName = `@paperclipai/adapter-${dir}`;
    if (fs.existsSync(pkgPath)) {
      try {
        pkgName = JSON.parse(fs.readFileSync(pkgPath, "utf-8")).name || pkgName;
      } catch { /* ignore */ }
    }
    const hasServer = fs.existsSync(path.join(adaptersDir, dir, "src/server"));
    const hasUi = fs.existsSync(path.join(ROOT, "ui/src/adapters", dir));
    md += `| \`${pkgName}\` | \`adapters/${dir}\` | ${hasServer ? "✅" : "❌"} | ${hasUi ? "✅" : "❌"} |\n`;
  }

  // Check for UI adapter dirs not matching a package
  const uiAdaptersDir = path.join(ROOT, "ui/src/adapters");
  if (fs.existsSync(uiAdaptersDir)) {
    const uiAdapters = fs.readdirSync(uiAdaptersDir).filter((d) => {
      return fs.statSync(path.join(uiAdaptersDir, d)).isDirectory();
    }).sort();
    md += `\n## UI Adapter Renderers (${uiAdapters.length})\n\n`;
    md += `| Directory |\n|-----------|\n`;
    for (const d of uiAdapters) {
      md += `| \`ui/src/adapters/${d}/\` |\n`;
    }
  }

  md += `\n> ⚠️ **Three registries rule:** Every adapter must have entries in server, CLI, AND UI. See \`CONVENTIONS.md\`.\n`;

  return md;
}

function generateContextIndex(): string {
  let md = `# .context/ — Machine-Readable Context for AI Agents\n\n`;
  md += `> Auto-generated by \`scripts/generate-context.ts\` on ${timestamp}\n`;
  md += `> Regenerate with: \`pnpm context:generate\`\n\n`;
  md += `These files exist so AI agents can **verify** what exists in the codebase\n`;
  md += `before referencing it — preventing hallucination of file names, function\n`;
  md += `names, types, API endpoints, and schema tables.\n\n`;
  md += `## Files\n\n`;
  md += `| File | What it contains |\n`;
  md += `|------|------------------|\n`;
  md += `| [shared-exports.md](shared-exports.md) | All types, constants, validators exported from \`@paperclipai/shared\` |\n`;
  md += `| [schema-snapshot.md](schema-snapshot.md) | All database tables exported from \`@paperclipai/db\` |\n`;
  md += `| [api-surface.md](api-surface.md) | All API routes mounted in the Express server |\n`;
  md += `| [adapter-registry.md](adapter-registry.md) | All adapters and their registration status |\n\n`;
  md += `## How to Use\n\n`;
  md += `**Before importing a type:** Check \`shared-exports.md\` → is the type listed?\n`;
  md += `**Before querying a table:** Check \`schema-snapshot.md\` → is the table listed?\n`;
  md += `**Before calling an API:** Check \`api-surface.md\` → is the route listed?\n`;
  md += `**Before adding an adapter:** Check \`adapter-registry.md\` → all 3 registries?\n`;
  return md;
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main(): void {
  console.log("[generate-context] Starting context generation...");
  ensureDir(CONTEXT_DIR);

  const files: [string, () => string][] = [
    ["README.md", generateContextIndex],
    ["shared-exports.md", generateSharedExports],
    ["schema-snapshot.md", generateSchemaSnapshot],
    ["api-surface.md", generateApiSurface],
    ["adapter-registry.md", generateAdapterRegistry],
  ];

  for (const [filename, generator] of files) {
    const content = generator();
    const outPath = path.join(CONTEXT_DIR, filename);
    fs.writeFileSync(outPath, content, "utf-8");
    const lines = content.split("\n").length;
    console.log(`[generate-context] ✅ ${filename} (${lines} lines)`);
  }

  console.log(`[generate-context] Done! Files written to .context/`);
}

main();
